# Build stage
FROM maven:3.8-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run stage - Equivilent of eclipse-temurin
FROM cgr.dev/chainguard/jre:latest
WORKDIR /app

COPY --from=build /app/target/vuln-app-1.0.0.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
